services:
  apache:
    build: ./docker/apache
    container_name: apache
    ports:
      - "8088:80"
    networks:
      - my_app_network
    volumes:
      - ./public_html:/var/www/html
      - ./zig-out/bin/zig_cgi:/var/www/html/index.cgi
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5.27
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db_name
      MARIADB_USER: db_username
      MARIADB_PASSWORD: db_password
    networks:
      - my_app_network
    ports:
      - "8306:3306"
    volumes:
      - ./docker/mariadb/database.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - zdb_data:/var/lib/mysql

networks:
  my_app_network:
    driver: bridge

volumes:
  zdb_data:
